### ISSUE TITLE
Time Skew

### ISSUE THREAD

**Issue by michft-v** [aidansteele/ipv6-ghost-ship#1]
My read of the Go code has the program only matching in the 30 second TOTP window. In a lot of TOTP aplications, there is an allowance for one or both clocks to have some time Skew or packets to be routing on the internet until after the aceptance window. This is covered by having a larger group of accepted numbers

Could this be modified to allow codes from of 30 seconds each side?
Could the size buffer be user configurable?

**Comment by aidansteele** [comment]
G'day!

Good question. On this line of code I am using the package-level `totp.Validate()`:

https://github.com/aidansteele/ipv6-ghost-ship/blob/2c58211787b630b26adf44b469ce37b27045c5fc/main.go#L51

Which has a default skew of `1`, i.e. 30 seconds forwards and backwards. Do you think this could be better documented? Do you think the readme or maybe a comment above that line would be better?

https://github.com/pquerna/otp/blob/60112ee2a95553a491c22956619ef30260ec93e8/totp/totp.go#L57
